#!/bin/bash

set -e

case "$1" in
  purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    # Recreate the /opt directory, since we are
    # ignoring Debian Policy by intentionally installing here..

    if [ ! -e /opt ]; then
        if mkdir /opt 2>/dev/null; then
            chown root:root /opt
            chmod 775 /opt
        fi
    fi
;;

*)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
;;
esac

exit 0
